### PR TITLE
Fix/types

### LINKED ISSUE #136: TypeScript: PrismJS from npm is not assignable to Prism prop
The following code should compile, but it doesn't:

```tsx
import Highlight from 'prism-react-renderer'
import Prism from 'prismjs'

export default function App() {
    return <Highlight Prism={Prism}>{() => null}</Highlight>
}
```

https://codesandbox.io/s/prism-react-renderer-ts-issue-ongu6

Error for Googleability:

```text
No overload matches this call.
  Overload 1 of 2, '(props: HighlightProps | Readonly<HighlightProps>): Highlight', gave the following error.
    Type 'typeof import("/sandbox/node_modules/@types/prismjs/index")' is not assignable to type 'PrismLib'.
      Types of property 'languages' are incompatible.
        Type 'Languages' is missing the following properties from type 'LanguageDict': markup, bash, clike, c, and 28 more.
  Overload 2 of 2, '(props: HighlightProps, context: any): Highlight', gave the following error.
    Type 'typeof import("/sandbox/node_modules/@types/prismjs/index")' is not assignable to type 'PrismLib'
```

### PR DESCRIPTION
**Pull request by narinluangrath**
Two fixes to our type definitions and a no-op code change

1. `Prism.tokenize` only takes two arguments not three
2. Users can provider their own `PrismJS` module (closes #136)

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -1,5 +1,6 @@
 declare module "prism-react-renderer" {
   import * as React from "react";
+  import type PrismJS from 'prismjs';
```
Comment (narinluangrath) [inline index.d.ts:3]: Is there additional work needed to ensure this type definition gets included in the npm package?

Comment (jpdriver) [reply index.d.ts:3]: no additional work needed -- `index.d.ts` is already included in the tar

**Review by jpdriver — APPROVED** [review]
LGTM nice catch @narinluangrath thanks
